# Used Chatgpt for TestCases
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: List Files for Debugging
        run: ls -la

      - name: Build Docker Image
        run: |
          docker build -t url-shortener-app .

      - name: Run Docker Container (Test)
        run: |
          docker run -d -p 5000:5000 --name url-shortener-container url-shortener-app
          sleep 10
          docker ps -a

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag url-shortener-app ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest